
name: Upload build folder to cPanel

on: push

jobs:
  upload:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install dependencies
      run: yarn
    
    - name: Build project
      run: yarn run build
    
    - name: Upload build folder
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ftp.intricatedesignspaces.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build/
        server-dir: /frontend/build/
